//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMIM_UserAccess_ST
    {
        public int CoAccId { get; set; }
        public int UserTypeId { get; set; }
        public int UserId { get; set; }
        public string Allow { get; set; }
    
        public virtual SMIM_UserMst_ST SMIM_UserMst_ST { get; set; }
        public virtual SMIM_UserType_ST SMIM_UserType_ST { get; set; }
    }
}
