/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sqe;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GenerateReport extends javax.swing.JFrame {

    /**
     * Creates new form GenerateReport
     */
    public GenerateReport() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    public boolean FileCreation() throws IOException
    {
       boolean downloaded = false;
       FileWriter myWriter = new FileWriter("LFADS.txt");
       myWriter.write("LFADS REPORT \n" + System.getProperty( "line.separator" ));
       myWriter.write("Ten posts have been fetched from your Facebook Timline and Analysed. "
               +" Analysis is as follow:\n");
       myWriter.write(System.getProperty( "line.separator" ));
       try {
            String url="jdbc:derby://localhost:1527/LFADS";
            java.sql.Connection con =  DriverManager.getConnection(url,null,null);
            Statement st = con.createStatement();
           
            String sql="SELECT * FROM POST";
            ResultSet rs = st.executeQuery(sql);
           
           
            int count = 0;
            while(rs.next())
            {  if(count < 10){
                int c = rs.getInt("ABUSECOUNT");
                String str1 = Integer.toString(c);
                String e = rs.getString("CONTENT");
                String f = rs.getString("PID");
                String filt = rs.getString("FILTEREDC");
                myWriter.write("Post Number : " + count + " \n"); //+" Original Post: \n"+f+"  "+e+"\n");
                myWriter.write(System.getProperty( "line.separator" ));
                myWriter.write("Post ID : " + f + " , Original Post: \n"+e+"\n");
                myWriter.write(" \n, No. of Abusive Words Used: "+c+"\n");
                myWriter.write(" \n, Filtered Version: "+filt+" \n\n");
                  myWriter.write(System.getProperty( "line.separator" ));
                count++;
                if(count == 10)
                {
                    System.out.println("File Downloaded!!!");
                    downloaded = true;
                }
                }
                else
                {
                    break;
                }
           }
        }
        catch (SQLException ex) {
            Logger.getLogger(GenerateReport.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       myWriter.close();
       return downloaded;
    }

    public void fetch()
    {
        try {
            DefaultTableModel model = new DefaultTableModel(new String[]{"PID", "Post", "AbuseCount","Filtered Post"}, 0);
            String url="jdbc:derby://localhost:1527/LFADS";
            java.sql.Connection con =  DriverManager.getConnection(url,null,null);
            Statement st = con.createStatement();
            
            String sql="SELECT * FROM POST";
            ResultSet rs = st.executeQuery(sql);
            
            int count =0;
            while(rs.next())
            {  if(count<10){
                
                int c = rs.getInt("ABUSECOUNT");
                String str1 = Integer.toString(c);
                String e = rs.getString("CONTENT");
                String f = rs.getString("PID");
                String filt = rs.getString("FILTEREDC");
                model.addRow(new Object[]{f,e,c,filt});
                System.out.println("Post ID: " + f + ", Original Post: " + e + 
                        ",\n Abuse Count: " + c + ", Filtered Post: " + filt);
                count++;
                
            } else
            {
                break;
            }
            
            }
            
            jTable2.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(GenerateReport.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 770));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REPORT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 290, 80, 20);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PID", "Post", "AbuseCount", "Filtered Post"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 340, 890, 190);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LANGUAGE FILTER AND ABUSE DETECTION SYSTEM");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 10, 630, 30);

        jLayeredPane1.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane1.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Download Report");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jButton1);
        jButton1.setBounds(40, 50, 190, 70);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GENERATED REPORT");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(40, 10, 200, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqe/doc.png"))); // NOI18N
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(310, 0, 100, 140);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(290, 80, 420, 160);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqe/bg2.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1000, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            // TODO add your handling code here:
            FileCreation();
        } catch (IOException ex) {
            Logger.getLogger(GenerateReport.class.getName()).log(Level.SEVERE, null, ex);
        }
     int a=JOptionPane.showConfirmDialog(null,"Downloading your report. Thank you for using LFADS!\n\tDo you want to exit?","Do you want to exit?",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.ERROR_MESSAGE);  
     if(a==JOptionPane.YES_OPTION){
     JOptionPane.showMessageDialog(null, "Goodbye");   
     System.exit(1);
}        
        
     //   JOptionPane.showMessageDialog(null, " "); 
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                     
                    
               GenerateReport r = new GenerateReport();
               r.fetch();
               r.setVisible(true);
                
            }
        });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables





}
