//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSMSService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyRespondent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyRespondent()
        {
            this.RespondentAnswers = new HashSet<RespondentAnswer>();
        }
    
        public long RespondentId { get; set; }
        public string RespondentName { get; set; }
        public byte RespondentAge { get; set; }
        public string RespodentEmail { get; set; }
        public string RespondentContact { get; set; }
        public long QuestionnaireId { get; set; }
    
        public virtual Questionnaire Questionnaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespondentAnswer> RespondentAnswers { get; set; }
    }
}
