//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSMSService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.Questionnaires = new HashSet<Questionnaire>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string LoginPassword { get; set; }
        public string FatherName { get; set; }
        public string Cnic { get; set; }
        public string Email { get; set; }
        public string UserAddress { get; set; }
        public string Department { get; set; }
        public string Organization { get; set; }
        public byte UserType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questionnaire> Questionnaires { get; set; }
        public virtual UserType UserType1 { get; set; }
    }
}
