//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSMSService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespondentAnswer
    {
        public long RespondentAnswerId { get; set; }
        public string RespondentAnswerValue { get; set; }
        public long OptionId { get; set; }
        public long RespondentId { get; set; }
    
        public virtual Option Option { get; set; }
        public virtual SurveyRespondent SurveyRespondent { get; set; }
    }
}
