//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPSService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMAM_ReviewSiteTypes_ST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMAM_ReviewSiteTypes_ST()
        {
            this.SMIM_ReviewAccountSite_ST = new HashSet<SMIM_ReviewAccountSite_ST>();
        }
    
        public int SiteTypeID { get; set; }
        public string SiteTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMIM_ReviewAccountSite_ST> SMIM_ReviewAccountSite_ST { get; set; }
    }
}
