//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPSService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSA_Organization_ST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMSA_Organization_ST()
        {
            this.SMSA_CompanyMst_ST = new HashSet<SMSA_CompanyMst_ST>();
            this.SMIM_UserMst_ST = new HashSet<SMIM_UserMst_ST>();
        }
    
        public int OrgID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string UserName { get; set; }
        public Nullable<int> SaleAccId { get; set; }
        public string Reference { get; set; }
        public string OrgType { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSA_CompanyMst_ST> SMSA_CompanyMst_ST { get; set; }
        public virtual SRCC_SalesAccount_ST SRCC_SalesAccount_ST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMIM_UserMst_ST> SMIM_UserMst_ST { get; set; }
    }
}
