//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPSService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRCC_GooglePlusReviews_TR
    {
        public int ID { get; set; }
        public int GoogleID { get; set; }
        public string GoogleReviewID { get; set; }
        public string Text { get; set; }
        public string Author { get; set; }
        public Nullable<decimal> OverallRating { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> Entered { get; set; }
        public Nullable<System.DateTime> AlertDate { get; set; }
        public int ReviewStatusID { get; set; }
        public string Note { get; set; }
    
        public virtual SRCC_GooglePlus_TR SRCC_GooglePlus_TR { get; set; }
        public virtual SRCC_ReviewStatusTypes_ST SRCC_ReviewStatusTypes_ST { get; set; }
    }
}
