//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPSService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRCC_SalesAccount_ST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SRCC_SalesAccount_ST()
        {
            this.SMSA_CompanyMst_ST = new HashSet<SMSA_CompanyMst_ST>();
            this.SMSA_Organization_ST = new HashSet<SMSA_Organization_ST>();
            this.SRCC_SalesAccount_ST1 = new HashSet<SRCC_SalesAccount_ST>();
            this.SMIM_UserMst_ST = new HashSet<SMIM_UserMst_ST>();
        }
    
        public int SaleAccId { get; set; }
        public string SaleAccount { get; set; }
        public string AccountCode { get; set; }
        public string AccountType { get; set; }
        public Nullable<int> ParentSaleId { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSA_CompanyMst_ST> SMSA_CompanyMst_ST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSA_Organization_ST> SMSA_Organization_ST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRCC_SalesAccount_ST> SRCC_SalesAccount_ST1 { get; set; }
        public virtual SRCC_SalesAccount_ST SRCC_SalesAccount_ST2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMIM_UserMst_ST> SMIM_UserMst_ST { get; set; }
    }
}
