/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqe;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ammara
 */
public class Welcx extends javax.swing.JFrame {

    /**
     * Creates new form Welcx
     */
    
    String entuser;
    String entpass;
    public static String currentuser;
    
    public Welcx() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        Laptimage = new javax.swing.JButton();
        noaccount = new javax.swing.JLabel();
        signinb = new javax.swing.JButton();
        cancelb = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(808, 770));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LANGUAGE FILTER AND ABUSE DETECTION SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 44));

        user.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        user.setText("User Name");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 419, 60));

        Laptimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqe/manlapt.jpeg"))); // NOI18N
        Laptimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptimageActionPerformed(evt);
            }
        });
        getContentPane().add(Laptimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 430, 250));

        noaccount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        noaccount.setText("Don't have an account yet?");
        noaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noaccountMouseClicked(evt);
            }
        });
        getContentPane().add(noaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 180, 30));

        signinb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        signinb.setText("Sign in");
        signinb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinbMouseClicked(evt);
            }
        });
        signinb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbActionPerformed(evt);
            }
        });
        getContentPane().add(signinb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 640, 210, 60));

        cancelb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cancelb.setText("Cancel");
        cancelb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelbMouseClicked(evt);
            }
        });
        getContentPane().add(cancelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 640, 210, 60));

        pass.setText("jPasswordField1");
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 420, 60));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 620, 670));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqe/bg2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void LaptimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptimageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptimageActionPerformed

    private void signinbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_signinbActionPerformed

    private void noaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noaccountMouseClicked

        dispose();
        try {
            CreateAcc.main(null);

        } catch (SQLException ex) {
            Logger.getLogger(Welcx.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_noaccountMouseClicked

    private void cancelbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbMouseClicked

     
 int a=JOptionPane.showConfirmDialog(null,"Are you sure?","Do you want to exit?",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.ERROR_MESSAGE);  
 if(a==JOptionPane.YES_OPTION)
 {
    JOptionPane.showMessageDialog(null, "Goodbye");   
    System.exit(1);
 }        

    }//GEN-LAST:event_cancelbMouseClicked

    private void signinbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinbMouseClicked

 
        entuser = user.getText();
        entuser.trim();
        entpass = String.valueOf(pass.getPassword());
        entpass.trim();
        
        if(Verify(entuser,entpass))
        {
            dispose();
            ReportG.main(null);
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "Entered Credentials are incorrect!");
        }
        
    }//GEN-LAST:event_signinbMouseClicked

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public boolean Verify(String name, String passw)
    {
        boolean flag = false;
        try
        {
            String url="jdbc:derby://localhost:1527/LFADS";
            java.sql.Connection con =  DriverManager.getConnection(url,null,null);
            Statement st = con.createStatement();
            
            ResultSet search = st.executeQuery("select * from USERR where username = '"+name+ "'AND password = '" + passw + "'"  );
            
            while(search.next())
            {
                flag = true;
                currentuser = name;
            }
          
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(Welcx.class.getName()).log(Level.SEVERE, null, ex);
        }
        return flag;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcx().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Laptimage;
    private javax.swing.JButton cancelb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel noaccount;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton signinb;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
