//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMAM_Menu_ST
    {
        public int MenuId { get; set; }
        public Nullable<int> ParentMenuId { get; set; }
        public string MenuType { get; set; }
        public string MenuDescription { get; set; }
        public string IconPath { get; set; }
        public Nullable<int> MenuSeq { get; set; }
        public string urlPath { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string RoleName { get; set; }
        public string LocalizeId { get; set; }
    }
}
