export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const AUTH_LOADING = 'AUTH_LOADING'

//users
export const USER_LOADING = 'USER_LOADING'
export const USERS_LOADING = 'USERS_LOADING'
export const USER_SAVED = 'USER_SAVED'
export const GET_USER = 'GET_USER'
export const GET_USERS = 'GET_USERS'
export const USERS_ERROR = 'USERS_ERROR'
export const USER_ERROR = 'USER_ERROR'
export const USER_DELETED = 'USER_DELETED'
export const USER_UPDATED = 'USER_UPDATED'
export const PASSWORD_UPDATED = 'PASSWORD_UPDATED'
export const PASSWORD_ERROR = 'PASSWORD_ERROR'
export const CODE_VERIFIED = 'CODE_VERIFIED'
export const VERIFCATION_ERROR = 'VERIFCATION_ERROR'

//events
export const GET_R_EVENT = 'GET_R_EVENT'
export const GET_REMOVEDEVENTS = 'GET_REMOVEDEVENTS'
export const EVENTS_LOADING = 'EVENTS_LOADING'
export const EVENT_LOADING = 'EVENT_LOADING'
export const EVENT_SAVED = 'EVENT_SAVED'
export const GET_EVENT = 'GET_EVENT'
export const GET_EVENTS = 'GET_EVENTS'
export const GET_BEVENTS = 'GET_BEVENTS'
export const EVENTS_ERROR = 'EVENTS_ERROR'
export const EVENT_ERROR = 'EVENT_ERROR'
export const EVENT_DELETED = 'EVENT_DELETED'
export const EVENT_UPDATED = 'EVENT_UPDATED'
export const EVENT_CLOSED = 'EVENT_CLOSED'

//change page
export const CHANGE_PAGE = 'CHANGE_PAGE'

//alerts
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

//products
export const PRODUCT_LOADING = 'PRODUCT_LOADING'
export const GET_QTY = 'GET_QTY'
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING'
export const PRODUCT_SAVED = 'PRODUCT_SAVED'
export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR'
export const PRODUCT_ERROR = 'PRODUCT_ERROR'
export const PRODUCT_DELETED = 'PRODUCT_DELETED'
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED'
export const IMAGES_SAVED = 'IMAGES_SAVED'
//customers
export const CUSTOMER_LOADING = 'CUSTOMER_LOADING'
export const CUSTOMERS_LOADING = 'CUSTOMERS_LOADING'
export const CUSTOMER_SAVED = 'CUSTOMER_SAVED'
export const GET_CUSTOMER = 'GET_CUSTOMER'
export const GET_CUSTOMERS = 'GET_CUSTOMERS'
export const CUSTOMERS_ERROR = 'CUSTOMERS_ERROR'
export const CUSTOMER_ERROR = 'CUSTOMER_ERROR'
export const CUSTOMER_DELETED = 'CUSTOMER_DELETED'
export const CUSTOMER_UPDATED = 'CUSTOMER_UPDATED'
export const SEARCHED_CUSTOMER = 'SEARCHED_CUSTOMER'
export const GET_INSIGHT = 'GET_INSIGHT'
export const INSIGHT_ERROR = 'INSIGHT_ERROR'
export const INSIGHT_LOADING = 'INSIGHT_LOADING'

//rentproduct
export const RENTPRODUCT_LOADING = 'RENTPRODUCT_LOADING'
export const RENTPRODUCTS_LOADING = 'RENTPRODUCTS_LOADING'
export const RENTPRODUCT_SAVED = 'RENTPRODUCT_SAVED'
export const GET_RENTPRODUCT = 'GET_RENTPRODUCT'
export const GET_RENTPRODUCTS = 'GET_RENTPRODUCTS'
export const GET_LASTRECORD = 'GET_LASTRECORD'
export const RENTPRODUCT_ERROR = 'RENTPRODUCT_ERROR'
export const RENTPRODUCTS_ERROR = 'RENTPRODUCTS_ERROR'
export const RENTPRODUCT_DELETED = 'RENTPRODUCT_DELETED'
export const RENTPRODUCT_UPDATED = 'RENTPRODUCT_UPDATED'
export const RENTPRODUCT_READY = 'RENTPRODUCT_READY'
export const RENTPRODUCT_ACTIVE = 'RENTPRODUCT_ACTIVE'
export const RENTPRODUCT_CANCEL = 'RENTPRODUCT_CANCEL'
export const RENTPRODUCT_ITEMS = 'RENTPRODUCT_ITEMS'
export const RENTPRODUCT_STATUS_SEARCH = 'RENTPRODUCT_STATUS_SEARCH'

//returnproduct
export const RETURNPRODUCT_LOADING = 'RETURNPRODUCT_LOADING'
export const RETURNPRODUCTS_LOADING = 'RETURNPRODUCTS_LOADING'
export const RETURNPRODUCT_SAVED = 'RETURNPRODUCT_SAVED'
export const GET_RETURNPRODUCT = 'GET_RETURNPRODUCT'
export const GET_RETURNPRODUCTS = 'GET_RETURNPRODUCTS'
export const RETURNPRODUCT_ERROR = 'RETURNPRODUCT_ERROR'
export const RETURNPRODUCTS_ERROR = 'RETURNPRODUCTS_ERROR'
export const RETURNPRODUCT_DELETED = 'RETURNPRODUCT_DELETED'
export const RETURNPRODUCT_UPDATED = 'RETURNPRODUCT_UPDATED'
export const GET_RETURNORDER = 'GET_RETURNORDER'
export const EMPTY_RETURN_ORDER = 'EMPTY_RETURN_ORDER'
export const GET_BARCODE_ORDER ="GET_BARCODE_ORDER"

//orders

export const ORDER_LOADING = 'ORDER_LOADING'
export const ORDERS_LOADING = 'ORDERS_LOADING'
export const ORDER_SAVED = 'ORDER_SAVED'
export const GET_ORDER = 'GET_ORDER'
export const GET_ORDERS = 'GET_ORDERS'
export const ORDER_ERROR = 'ORDER_ERROR'
export const ORDERS_ERROR = 'ORDERS_ERROR'
export const ORDER_DELETED = 'ORDER_DELETED'
export const ORDER_UPDATED = 'ORDER_UPDATED'
export const GET_COUNT_ORDERS = 'GET_COUNT_ORDERS'


// alter notes
export const ALTERNOTES_LOADING = 'ALTERNOTES_LOADING'
export const ALTERNOTES_ERROR = 'ALTERNOTES_ERROR'
export const GET_ALTERNOTES = 'GET_ALTERNOTES'
export const ADD_ALTERNOTE = 'ADD_ALTERNOTES'
export const DONE_ALTERNOTE = 'DONE_ALTERNOTE'

//appointment

export const APPOINTMENT_LOADING = 'APPOINTMENT_LOADING'
export const APPOINTMENTS_LOADING = 'APPOINTMENTS_LOADING'
export const APPOINTMENT_SAVED = 'APPOINTMENT_SAVED'
export const GET_APPOINTMENT = 'GET_APPOINTMENT'
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS'
export const APPOINTMENT_ERROR = 'APPOINTMENT_ERROR'
export const APPOINTMENTS_ERROR = 'APPOINTMENTS_ERROR'
export const APPOINTMENT_DELETED = 'APPOINTMENT_DELETED'
export const APPOINTMENTS_CHECKEDIN = 'APPOINTMENTS_CHECKEDIN'
export const APPOINTMENTS_CANCEL = 'APPOINTMENTS_CANCEL'
export const GET_TODAYS_APPOINTMENTS='GET_TODAYS_APPOINTMENTS'
export const APPOINTMENT_UPDATED = 'APPOINTMENT_UPDATED'
//report
export const GET_REPORT = 'GET_REPORT'
export const REPORT_ERROR = 'REPORTS_ERROR'
export const REPORT_LOADING = 'REPORT_LOADING'

// dashbaord
export const SHOP_STARTED = 'SHOP_STARTED'
export const SHOP_STOPPED = 'SHOP_STOPPED'
export const DASHBOARD_LOADING = 'DASHBOARD_LOADING'
export const DASHBOARD_LOADED = 'DASHBOARD_LOADED'
export const DASHBOARD_ERROR = 'DASHBOARD_ERROR'
export const SHOP_LOADING = 'SHOP_LOADING'
export const SHOP_LOADED = 'SHOP_LOADED'
export const SHOP_ERROR = 'SHOP_ERROR'

//Invoices

export const INVOICE_LOADING = 'INVOICE_LOADING'
export const INVOICES_LOADING = 'INVOICES_LOADING'
export const INVOICE_SAVED = 'INVOICE_SAVED'
export const GET_INVOICE = 'GET_INVOICE'
export const GET_INVOICES = 'GET_INVOICES'
export const INVOICES_ERROR = 'INVOICES_ERROR'
export const INVOICE_ERROR = 'INVOICE_ERROR'
export const INVOICE_DELETED = 'INVOICE_DELETED'
export const INVOICE_UPDATED = 'INVOICE_UPDATED'


//customers
export const GET_COUPONS = 'GET_COUPONS'
export const COUPON_LOADING = 'COUPON_LOADING'
export const COUPON_ERROR = 'COUPON_ERROR'
export const GET_COUPON = 'GET_COUPON'
export const COUPON_DELETED = 'COUPON_DELETED'
export const COUPON_SAVED = 'COUPON_SAVED'
export const COUPON_UPDATED = 'COUPON_UPDATED'
