//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPSService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMIM_ReviewAccounts_ST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMIM_ReviewAccounts_ST()
        {
            this.SMIM_ReviewAccountSite_ST = new HashSet<SMIM_ReviewAccountSite_ST>();
        }
    
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public int AccountTypeID { get; set; }
        public string Description { get; set; }
        public bool Inactive { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Credentials { get; set; }
        public string PhoneNumber { get; set; }
        public string Website { get; set; }
        public string NPI { get; set; }
        public string Specialty { get; set; }
        public string StoreCode { get; set; }
        public Nullable<int> ReviewPullType { get; set; }
        public Nullable<int> ProfilePullType { get; set; }
        public Nullable<bool> IsBenchmarkAccount { get; set; }
        public string Comments { get; set; }
    
        public virtual SMSA_CompanyMst_ST SMSA_CompanyMst_ST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMIM_ReviewAccountSite_ST> SMIM_ReviewAccountSite_ST { get; set; }
        public virtual SMIM_AccountType_ST SMIM_AccountType_ST { get; set; }
    }
}
