//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPSService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSA_CompanyMst_ST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMSA_CompanyMst_ST()
        {
            this.SMIM_ReviewAccounts_ST = new HashSet<SMIM_ReviewAccounts_ST>();
            this.SMIM_UserMst_ST = new HashSet<SMIM_UserMst_ST>();
        }
    
        public int OrgID { get; set; }
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string logoPath { get; set; }
        public string EstID { get; set; }
        public Nullable<int> TotalEmp { get; set; }
        public string Activity { get; set; }
        public string Salutation { get; set; }
        public string ContactPerson { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public int CityID { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string VerifyEmail { get; set; }
        public Nullable<int> SaleAccId { get; set; }
        public string IsActive { get; set; }
        public string IsApproved { get; set; }
        public string Terms { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> SifCharges { get; set; }
        public string WPSUserId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMIM_ReviewAccounts_ST> SMIM_ReviewAccounts_ST { get; set; }
        public virtual SMSA_Organization_ST SMSA_Organization_ST { get; set; }
        public virtual SRCC_SalesAccount_ST SRCC_SalesAccount_ST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMIM_UserMst_ST> SMIM_UserMst_ST { get; set; }
    }
}
