//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPSService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSA_Areas_ST
    {
        public int AreaID { get; set; }
        public string Title { get; set; }
        public string CityName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
    
        public virtual SMSA_Country_ST SMSA_Country_ST { get; set; }
        public virtual SMSA_States_ST SMSA_States_ST { get; set; }
        public virtual SMSA_City_ST SMSA_City_ST { get; set; }
        public virtual SMSA_City_ST SMSA_City_ST1 { get; set; }
    }
}
