//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPSService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRCC_GooglePlus_TR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SRCC_GooglePlus_TR()
        {
            this.SRCC_GooglePlusReviews_TR = new HashSet<SRCC_GooglePlusReviews_TR>();
        }
    
        public int ID { get; set; }
        public int SiteAccountID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> OverallRating { get; set; }
        public int ReviewCount { get; set; }
        public string APIReference { get; set; }
    
        public virtual SMIM_ReviewAccountSite_ST SMIM_ReviewAccountSite_ST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRCC_GooglePlusReviews_TR> SRCC_GooglePlusReviews_TR { get; set; }
    }
}
